### PR TITLE
Adding the possibility to add account manually

### PR DESCRIPTION
**Pull request by jtyr**
This patch contains the following changes:

- Adding the possibility to add account manually without the need to
  scan the QR code. It requires to fill in the name of the account
  the secret key and choose one of the authentication type (TOTP, HOTP).
- Support for Issuer in the list of codes. It's automatically extracted
  from the account name if it's in the issuer:label format.
- Updated icons for multiple screen resolutions.
- General cleanup of the code based on Android Studio suggestions.

### CODE REVIEW

**Comment by dainnilsson** [comment]
Thanks for this! I'm going to have to ask you for two things before I can merge this:
1. Please state that you agree to contribute the changes you have made to the project under the license of the project (BSD 2 clause).
2. Please rebase your pull request splitting the changes into smaller commits, each with a a description of the change. The four bullets you have listed in your comment would do fine.

**Comment by jtyr** [comment]
Yes, I agree to contribute my code under the BSD license. The splitting into multiple commits is a bit difficult now because the changes are interconnected.

**Comment by jtyr** [comment]
Please does this patch have a chance to be merged without the need to split the changes into multiple commits?

**Comment by dainnilsson** [comment]
I've spent a bit more time looking at the code, and I'm going to have to reject it I'm afraid. There are too many things going that should really be in separate pull requests so that each one can be evaluated separately. 
Some feedback I can give you, from what I've gathered by scanning over the code:

* Manual account creation:
We definitely want this feature. I'm not sure I think adding a new Fragment is the best approach. I'd prefer re-using the existing fragment instead, just slightly altered. I would add a text field for the secret, and either pass it data from an OATH URL, or launch it without data for manual entry. If the secret is passed to it from a URL I would hide the field, as the user wouldn't have any need of changing it.

* Support Issuer in list of codes:
As far as I can see, this only changes the way the codes are displayed, by breaking the issuer into a separate view? If so then that's probably fine, assuming it improves the UI.

* Updated icons for multiple resolutions:
Some of the icons have been changed, but I'm not able to see any visual change to them. Other icons that have been added/replaced aren't consistent with others, as some have black outlines where others do not. So far I haven't noticed any issues with only providing icons in one size. Is this change really needed?

* Android Studio suggested changes:
I don't see much benefit to this type of changes, but I also don't see much harm in them. In a pull request by themselves I wouldn't mind merging them, assuming there is a description of why the changes were made.

**Comment by jtyr** [comment]
Thanks for your feedback. Here are my comments:

- New fragment is easier to maintain. I was considering to alter the existing one but it seemed to be too invasive change which would lead to less readable code.
- Yes, the issuer is just small tweak to split the current label into two textviews.
- Icons for multiple resolutions is a must for high-res devices. Without them you end up having blurred icon edges (as it was with the original icons I have replaced).
- Suggestions made by Andoid Studio are always good to implement as they improve stability and compatibility of the code with the specified APIs (min and target version from the Android Manifest). For example the old code had too many place with a danger of NullPointer exceptions.

The additional changes () I have done are very minor changes which I did along the main feature (Manual account creating). This is why it's so difficult to split it into multiple changes. I would really appreciate if you would test my code and eventually merge it as I spent significant time on implementing this feature which is often requested by so many users.

**Comment by dainnilsson** [comment]
I'm sorry, but my answer is final. It would take more time/effort to review all changes together than it would take to implement the feature itself. That in combination with the additional changes that we're not interested in, and the fact that the changes are all bunched in a single commit I just can't merge this. I appreciate the time you've spent on this feature, and you're right that it's one of the most requested features by our users. We will be adding the feature, most likely in the next release.

**Comment by jtyr** [comment]
I understand. I have split the changes into three pull requests (#14, #15, #16). This time I'm not trying to fix any code which is not related to the change itself. I believe this makes it much easier for you to review.

**Pull request closed without merging**
